# Generated by Django 5.2.1 on 2025-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="community_icons/"
            ),
        ),
    ]
