# Generated by Django 5.2.1 on 2025-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_community_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
