# Generated by Django 5.2.1 on 2025-05-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_community_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_type",
            field=models.CharField(
                choices=[("text", "Text"), ("calendar", "Calendar"), ("poll", "Poll")],
                default="text",
                max_length=10,
            ),
        ),
    ]
