# Generated by Django 5.2.1 on 2025-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
