# Generated by Django 5.2.1 on 2025-05-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("titulo", models.CharField(max_length=255)),
                ("sinopse", models.TextField(blank=True, null=True)),
                ("diretor", models.CharField(blank=True, max_length=255, null=True)),
                ("elenco", models.JSONField(default=list)),
                ("genero", models.JSONField(default=list)),
                ("avaliacao_media", models.FloatField(default=0.0)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_lancamento", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Filme",
                "verbose_name_plural": "Filmes",
                "ordering": ["-data_lancamento"],
            },
        ),
    ]
