# Generated by Django 5.2.1 on 2025-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filme",
            name="avaliacao_media",
        ),
        migrations.RemoveField(
            model_name="filme",
            name="backdrop_path",
        ),
        migrations.RemoveField(
            model_name="filme",
            name="diretor",
        ),
        migrations.RemoveField(
            model_name="filme",
            name="elenco",
        ),
        migrations.RemoveField(
            model_name="filme",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="filme",
            name="poster_path",
        ),
        migrations.AddField(
            model_name="filme",
            name="adulto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filme",
            name="atores_principais",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="filme",
            name="backdrop_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="diretores",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="filme",
            name="duracao",
            field=models.IntegerField(
                blank=True, help_text="Duração em minutos", null=True
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="generos",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="filme",
            name="idioma_original",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="nota_media",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="filme",
            name="orcamento",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="receita",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="site_oficial",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="filme",
            name="total_votos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filme",
            name="video",
            field=models.BooleanField(default=False),
        ),
    ]
