# Generated by Django 5.2.1 on 2025-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_forumcomment_filmeuseraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmeuseraction",
            name="assistido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filmeuseraction",
            name="avaliacao",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
