# Generated by Django 5.2.1 on 2025-05-22 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_filmeuseraction_assistido_filmeuseraction_avaliacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmeuseraction",
            name="dislike",
        ),
        migrations.AlterField(
            model_name="filmeuseraction",
            name="filme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_actions",
                to="movies.filme",
            ),
        ),
        migrations.AlterField(
            model_name="filmeuseraction",
            name="like",
            field=models.IntegerField(
                blank=True,
                help_text="0 = não gostei, 1 = gostei, null = não votou",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filmeuseraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filme_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
